# Generated by Django 3.2.9 on 2021-11-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickloc',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='pickloc',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pickloc',
            name='pick_time',
            field=models.CharField(default='14:00', max_length=20),
        ),
        migrations.AddField(
            model_name='pickloc',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
