# Generated by Django 3.2.9 on 2021-12-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='ticket_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
