# Generated by Django 3.2.9 on 2021-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20211202_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='lineitem_total',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='pax_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='pax_fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='pax_tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
