# Generated by Django 3.2.9 on 2021-12-14 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211129_1848'),
        ('checkout', '0007_auto_20211211_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventrecord', to='events.eventlist'),
        ),
    ]
